// <auto-generated />
using System;
using System.Collections.Generic;
using MOHProject.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MOHProject.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711054710_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MOHProject.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId", "OccurredAt");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Insured", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Residency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Insureds", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Letter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId", "Type", "IsCurrent");

                    b.ToTable("Letters", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.LetterPlan", b =>
                {
                    b.Property<long>("LetterId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.HasKey("LetterId", "PlanId");

                    b.HasIndex("PlanId");

                    b.ToTable("LetterPlans", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Payer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Residency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payers", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Plan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasActiveExclusion")
                        .HasColumnType("bit");

                    b.Property<bool>("HasActiveRiskLoading")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBase")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelectedInProductTab")
                        .HasColumnType("bit");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("GrossPremium", "MOHProject.Domain.Entities.Plan.GrossPremium#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("GrossPremium_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("GrossPremium_Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PrivateInsuranceExtraPremium", "MOHProject.Domain.Entities.Plan.PrivateInsuranceExtraPremium#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrivateInsuranceExtraPremium_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PrivateInsuranceExtraPremium_Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Policy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InsuredId")
                        .HasColumnType("bigint");

                    b.Property<int>("InsuredResidency")
                        .HasColumnType("int");

                    b.Property<long?>("PayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("PayerResidency")
                        .HasColumnType("int");

                    b.Property<long?>("PolicyHolderId")
                        .HasColumnType("bigint");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("PremiumCollectionId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Substatus")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UwCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UwStateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsuredId");

                    b.HasIndex("PayerId");

                    b.HasIndex("PolicyHolderId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("PremiumCollectionId");

                    b.HasIndex("UwStateId");

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.PolicyHolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Residency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PolicyHolders", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.PremiumCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.ComplexProperty<Dictionary<string, object>>("BaseCollected", "MOHProject.Domain.Entities.PremiumCollection.BaseCollected#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BaseCollected_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("BaseCollected_Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("BaseToCollect", "MOHProject.Domain.Entities.PremiumCollection.BaseToCollect#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BaseToCollect_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("BaseToCollect_Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LinkedRidersCollected", "MOHProject.Domain.Entities.PremiumCollection.LinkedRidersCollected#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("LinkedRidersCollected_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("LinkedRidersCollected_Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LinkedRidersToCollect", "MOHProject.Domain.Entities.PremiumCollection.LinkedRidersToCollect#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("LinkedRidersToCollect_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("LinkedRidersToCollect_Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UnallocatedCash", "MOHProject.Domain.Entities.PremiumCollection.UnallocatedCash#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("UnallocatedCash_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("UnallocatedCash_Currency");
                        });

                    b.HasKey("Id");

                    b.ToTable("PremiumCollections", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Reminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ParentLetterId")
                        .HasColumnType("bigint");

                    b.Property<long>("PolicyId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReminderType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentLetterId");

                    b.HasIndex("PolicyId", "Status");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.UWState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AcceptCloa")
                        .HasColumnType("int");

                    b.Property<bool>("AcceptCloaEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("CompleteUw")
                        .HasColumnType("bit");

                    b.Property<int>("CurrentComposition")
                        .HasColumnType("int");

                    b.Property<bool>("RcmpFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("RcmpFlagEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("RcmpOption")
                        .HasColumnType("int");

                    b.Property<bool>("RcmpOptionEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UWStates", (string)null);
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("MOHProject.Domain.Entities.Policy", "Policy")
                        .WithMany("AuditEntries")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Letter", b =>
                {
                    b.HasOne("MOHProject.Domain.Entities.Policy", "Policy")
                        .WithMany("Letters")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.LetterPlan", b =>
                {
                    b.HasOne("MOHProject.Domain.Entities.Letter", "Letter")
                        .WithMany("IncludedPlans")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MOHProject.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Letter");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Plan", b =>
                {
                    b.HasOne("MOHProject.Domain.Entities.Policy", "Policy")
                        .WithMany("Plans")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Policy", b =>
                {
                    b.HasOne("MOHProject.Domain.Entities.Insured", "Insured")
                        .WithMany()
                        .HasForeignKey("InsuredId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MOHProject.Domain.Entities.Payer", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MOHProject.Domain.Entities.PolicyHolder", "PolicyHolder")
                        .WithMany()
                        .HasForeignKey("PolicyHolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MOHProject.Domain.Entities.PremiumCollection", "PremiumCollection")
                        .WithMany()
                        .HasForeignKey("PremiumCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MOHProject.Domain.Entities.UWState", "UWState")
                        .WithMany()
                        .HasForeignKey("UwStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Insured");

                    b.Navigation("Payer");

                    b.Navigation("PolicyHolder");

                    b.Navigation("PremiumCollection");

                    b.Navigation("UWState");
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("MOHProject.Domain.Entities.Letter", "ParentLetter")
                        .WithMany()
                        .HasForeignKey("ParentLetterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MOHProject.Domain.Entities.Policy", "Policy")
                        .WithMany("Reminders")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLetter");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Letter", b =>
                {
                    b.Navigation("IncludedPlans");
                });

            modelBuilder.Entity("MOHProject.Domain.Entities.Policy", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Letters");

                    b.Navigation("Plans");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
